<a href="https://colab.research.google.com/github/al34n1x/datascience/blob/master/modulo_2/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

>[Numpy](#scrollTo=N0GJeEJQRGBh)

>>[Comparando nmarrays y Python Arrays](#scrollTo=Q_VOhzu1VVkE)

>>[NumPy ndarray: Un objeto Array Multidimensional](#scrollTo=DlQjmD-7YZns)

>>[Creando Arrays](#scrollTo=9PWddxWrce5U)

>>[Tipo de datos](#scrollTo=UVBAQBG0gOTV)

>>[Aritmética con NumPy Array](#scrollTo=DQhuGqqahFe8)

>>[Slicing e Indexing básico](#scrollTo=_tF-mjZ_idWJ)

>>[Indexing con Slicing](#scrollTo=2pYCvStZoeUk)

>>[Slicing en array de dos dimensiones](#scrollTo=EtaiNVier6XI)

>>[Fancy Indexing](#scrollTo=BO0IJOvc0U7z)

>>[Funciones universales para el manejo de arrays](#scrollTo=qGdasrMY1sK8)

>[Programación con arrays](#scrollTo=bjMDpJi93Apj)



#Numpy

Numpy, es una combinación de palabras, `Numerical` y `Python`. Es uno de los paquetes más importantes en Python para el computo númerico.
La mayoría de los paquetes que proveen cálculos científicos utilizan objetos **NumPy** como elemento para intercambio de datos.

Estás son algunos elementos que utilizaremos con NumPy:

* **ndarray**: Una eficiente matriz *(Array=Arreglo)* multidimensional que provee operaciones aritmeticas entre arrays de forma flexible y rápidas.

* Funciones matemáticas para operar entre arrays de datos sin tener que escribir Loops. **AHHHH!**



&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <img src="https://pm1.narvii.com/6240/84538693599c0871fec9e10f1fd0586fd3c284c4_hq.jpg"  width="250" height="250" />

* Herramientas para escribir array en disco y trabajarlos con archivos mapeados en memoria

* Algebra lineal, generación aleatoria de números, y algunas transformaciones.

Debido a que NumPy provee una facil de usar API (Application Programming Interface) para interactuar con otros lenguajes como C, es muy directo pasar datos de una libería externa en bajo nivel a Python.

Mientras que NumPy por si mismo no provee ninguna funcionalidad de modelado o científica, entender arrays NumPy y computo de arrays, te ayudará a usar otras herramientas como **Pandas** más eficientemente.

Principalmente nos focalizaremos en: 

* Operaciones entre arrays, data mining, y data cleaning, Filtering y transformaciones.

* Operaciones entre Arrays.

* Manipulación de datos mediante unión y consolidación (Join, Merge) utilizando datasets heterogéneos.

* Condiciones lógicas aplicadas a arrays.

Mientras que NumPy provee las bases para calculo computacional genérico, científicos de datos utilizan Pandas como el pilar de la mayoría de los desarrollos estadísticos y analíticos, especialmente con Datos tabulares. Panda también provee algunas funcionalidades que son específicas del dominio como manipulación de series.


## Comparando nmarrays y Python Arrays

Una de las razones por las que NumPy es tan importante para computo númerico en Python es debido a su eficiencia en el manejo de largos arrays (Arreglos) de datos.

NumPy internamente almacena los datos de forma contigua en bloques de memoria, independientemente de otros objetos Python. La librería Numpy de algoritmo puede operar en memoria sin perdida de performance. Los arrays de Numpy ocupan menos espacio que las listas de Python.

**Cuál será la razón?**

![](https://media1.tenor.com/images/4704d511d603640b82c2aeed0cc3af31/tenor.gif?itemid=11691381)

.. Sigamos

Las operaciones NumPy se comportan mejor en operaciones computacionales complejas en arrays sin la necesidad de utilizar loops de Python.

Para darles una idea de la diferencia de performance, veamos el siguiente código aplicando NumPy Arrays y listas Python


In [0]:
import numpy as np
my_arr = np.arange(10000000)  # Utilizando NumPy Arrays
my_list = list(range(10000000)) # Utilizando Listas Python

In [0]:
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 186 ms, sys: 10.3 ms, total: 196 ms
Wall time: 202 ms
CPU times: user 6.37 s, sys: 1.5 s, total: 7.87 s
Wall time: 7.88 s


## NumPy ndarray: Un objeto Array Multidimensional
Uno de las principales capacidad de NumPy es el N-Dimensional array, o también conocido como **ndarray**, cual es un rápido, y flexible container de largos datasets.
Los arreglos permiten ejecutar operaciones matemáticas en un bloque completo usando sintaxis equivalente a elementos escalares.

Para darte una pequeña introducción de como NumPy puede gestionar arrays de forma similar que objetos Python, ejecutemos el siguiente código.


In [0]:
import numpy as np #Importamos Numpy
# Generamos Data random
data = np.random.randn(2, 3)
data

array([[ 0.26510728, -2.4343054 ,  1.69135634],
       [-0.59523144,  0.40002331, -0.68995011]])

In [0]:
data * 10

In [0]:
data * data #Multiplo - Corregir agregar Multiplo matrices 3 x 3

array([[0.07028187, 5.92584279, 2.86068626],
       [0.35430047, 0.16001865, 0.47603115]])

In [0]:
data.shape

In [0]:
data?

In [0]:
data.dtype

dtype('float64')

In [0]:
# Producto entre matrices
a = np.matrix([[1, 2], [3, 4]]) 
b = np.matrix([[2,3], [1,2]])

c = np.dot(a,b) #función producto de matrices
c


matrix([[ 4,  7],
        [10, 17]])

## Creando Arrays

La forma más simple de crear arrays es utilizando la función array. Dicha función acepta secuencia de objetos, incluidos otros arrays, y produce un nuevo array NumPy que contiene la data que se ha pasado. Por ejemplo:

In [0]:
data1 = [6, 7.5, 8, 0, 1] #Lista Python
arr1 = np.array(data1) #NumPy Array
arr1


Secuencias anidades, son convertidas a arrays multidimensionales.


In [0]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]] # Anido dos Listas
arr2 = np.array(data2) # Lo convierto en Array
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [0]:
arr2.ndim

2

In [0]:
arr2.shape

(2, 4)

In [0]:
data3 = [[1,2,3,4], arr1] #Que sucede aquí?
data3

Al menos que se especifique, **np.array** intenta inferir el mejor tipo de dato para el array creado. El tipo de dato es almacenado en un tipo especial de metadato. Por ejemplo:

In [0]:
arr1.dtype # Tipo de dato array1

dtype('float64')

In [0]:
arr2.dtype # Tipo de dato array2

dtype('int64')

Adicionalmente, **np.array** posee un número de funciones para crear nuevos arrays. Por ejemplo, crear arrays solo con ceros y unos respectivamente, con una dada longitud y forma.


In [0]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [0]:
arr4 = np.zeros((5, 10)) #3 filas 6 columnas de ceros
arr4

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Con una longitud particular, **np.empty** crea un array sin inicializar y sin valores particulares.

In [0]:
np.empty((4,3, 2)) #Array de 2 objetos de 3 filas y 2 columnas cada uno

In [0]:
np.arange(15)

## Tipo de datos

Puedes explicitamente convertir o castear un array de un tipo de dato a otro usando el método **astype** 


In [0]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [0]:
float_arr = arr.astype(np.float64) # Tomamos el array arr y lo casteamos a float
float_arr.dtype
print (float_arr)

[1. 2. 3. 4. 5.]


## Aritmética con NumPy Array

Arrays son importante porque permite expresar operaciones batch en datos sin tener que escribir loops. Cualquier operación aritmética entre arrays del mismo tamaño aplica la operación a través de los elementos.


In [0]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print (arr)
print ('\n')
print (arr * arr)
print ('\n')
print (arr - arr)
print ('\n')

In [0]:
print (1 / arr)
print ('\n')
print (arr ** 0.5)

In [0]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [0]:
arr2 > arr #Devolverá un True o False

array([[False,  True, False],
       [ True, False,  True]])

## Slicing e Indexing básico

Los índices en arrays NumPuy permiten seleccionar un subset individual de elementos. Los arrays simples son similares en comportamiento a las listas. Pero a medida que avanzamos, utilizar NumPy arrays es mucho mas útil.

In [0]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
print (arr[5])
print (arr[5:8])
arr[5:8] = 12
print (arr)

El slice vacío asignará el mismo valor a todo el array


In [0]:
arr_slice = np.zeros(10)
print(arr_slice)
arr_slice[:] = 64
arr_slice

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([64., 64., 64., 64., 64., 64., 64., 64., 64., 64.])

Con arrays de mayor dimensión, tienes muchas opciones. En un array de dos dimensiones, los elementos de cada índice no son más escalare, sino arrays de una dimensión.


In [0]:
import numpy as np
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[1:, :2]


array([[4, 5],
       [7, 8]])

Una forma fácil de ver los arrays multidimensionales es por ejemplo de la siguiente forma.
Tomamos el Eje 0 (axis 0) como las filas, y el Eje 1 (axis 1) como las columnas

<img src="https://github.com/al34n1x/datascience/blob/master/img/array.png?raw=true" width="400" height="300" />



## Indexing con Slicing

Indices y Slices funcionan de la misma manera en arrays que en listas.
Así mismo podemos combinar el uso de índices con slices para extraer subitems de posiciones específicas del array.

In [0]:
print (arr2d)
print ('\n')
arr2d[:2, 1:] # Del primer item extraemos los números desde la posición 1 en adelante, 
              # y del segundo ítem del array extraemos desde la posición 1 en adelante

In [0]:
list = [1,2,3,4,5]
list [1:3]

[2, 3]

Cuando rebanamos de esta forma, obtenemos vista de arrays dentro del mismo numero de dimensiones. Mezclando índices enteros y slides, podes obtener  rebanadas de una dimensión inferior.

Por ejemplo, puedo seleccionar la segunda fila pero solo las primeras dos columnas de la misma mediante la siguiente sentencia.


In [0]:
arr2d[:2, 0]

array([1, 4])

Similarmente, puedes seleccionar la tercera columna pero solo la primera fila con la siguiente sentencia.



In [0]:
print (arr2d)
print ('\n')
arr2d[:2, 2]

[[1 2 3]
 [4 5 6]
 [7 8 9]]




array([3, 6])

In [0]:
print (arr2d)
print ('\n')
arr2d[:, :1] #Que me mostrará?

[[1 2 3]
 [4 5 6]
 [7 8 9]]




array([[1],
       [4],
       [7]])

## Slicing en array de dos dimensiones

Este gráfico puede ayudarte durante tu trabajo desarrollando código con NumPy.


<img src="https://github.com/al34n1x/datascience/blob/master/img/array_shapes.png?raw=true" width="380" height="400" />


In [0]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Fancy Indexing

Fancy Indexing es un termino adoptado por NumPy para describir el uso de índices utilizando arreglos de enteros. Supongamos un array de  8 x 4:

In [0]:
arr = np.empty((8, 4))
for i in range(8):
  arr[i] = i

arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

Para seleccionar un subset de filas en un orden particular, simplemente le pasas una lista o un ndarray de enteros especificando el orden deseado:


In [0]:
arr[[4, 3, 0, 6]]

## Funciones universales para el manejo de arrays

Una función universal o **ufunc** es una función que puede aplicarse a todos los datos del ndarray. Puedes pensar como funciones simples que pueden tomar un valor escalar y producir muchos escalares como resultado.


In [0]:
arr = np.arange(10)
print(arr)
np.sqrt(arr) # Nos dara la raíz cuadrada de todos los elementos del array.

[0 1 2 3 4 5 6 7 8 9]


array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [0]:
np.exp(arr) # Que hará esta función?
np

Existen otras funciones binarias, que necesitan de dos argumentos para operar, por ejemplo las funciones Max o Min

In [0]:
x = np.random.randn(8)
y = np.random.randn(8)
np.maximum(x, y)

array([ 0.11324984,  0.84642197, -1.40405964,  1.45160208, -0.54261713,
       -0.96082837,  1.21378291,  0.29392378])

# Programación con arrays

Usar arrays Numpy permite expresar diferentes tipo de datos como expresiones concisas de arrays, que de otra manera requerirían utilizar loops.
Está práctica de reemplazaz de forma explicita el uso de loops con expresiones de array se conoce comunment como vectorización. En general, vectorizar operacioes de array serán mucho más rápidas que su contraparte pura en Python.

Como ejemplo, supongamos evaluar la función `sqrt(x^2 + y^2)` a través de una grilla de valores. La función **np.meshgrid** toma dos arrays de 1 dimension y produce dos arrays de dos dimensiones correspondiente al par (x,y) en dos arrays:



In [0]:
points = np.arange(0, 10, 0.01) # 1000 equally spaced points
xs = np.meshgrid(points, points)
ys = np.meshgrid(points, points)
ys

[array([[0.  , 0.01, 0.02, ..., 9.97, 9.98, 9.99],
        [0.  , 0.01, 0.02, ..., 9.97, 9.98, 9.99],
        [0.  , 0.01, 0.02, ..., 9.97, 9.98, 9.99],
        ...,
        [0.  , 0.01, 0.02, ..., 9.97, 9.98, 9.99],
        [0.  , 0.01, 0.02, ..., 9.97, 9.98, 9.99],
        [0.  , 0.01, 0.02, ..., 9.97, 9.98, 9.99]]),
 array([[0.  , 0.  , 0.  , ..., 0.  , 0.  , 0.  ],
        [0.01, 0.01, 0.01, ..., 0.01, 0.01, 0.01],
        [0.02, 0.02, 0.02, ..., 0.02, 0.02, 0.02],
        ...,
        [9.97, 9.97, 9.97, ..., 9.97, 9.97, 9.97],
        [9.98, 9.98, 9.98, ..., 9.98, 9.98, 9.98],
        [9.99, 9.99, 9.99, ..., 9.99, 9.99, 9.99]])]

In [0]:
z = np.sqrt(xs + ys)
z

array([[[0.        , 0.1       , 0.14142136, ..., 3.15753068,
         3.1591138 , 3.16069613],
        [0.        , 0.1       , 0.14142136, ..., 3.15753068,
         3.1591138 , 3.16069613],
        [0.        , 0.1       , 0.14142136, ..., 3.15753068,
         3.1591138 , 3.16069613],
        ...,
        [0.        , 0.1       , 0.14142136, ..., 3.15753068,
         3.1591138 , 3.16069613],
        [0.        , 0.1       , 0.14142136, ..., 3.15753068,
         3.1591138 , 3.16069613],
        [0.        , 0.1       , 0.14142136, ..., 3.15753068,
         3.1591138 , 3.16069613]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.1       , 0.1       , 0.1       , ..., 0.1       ,
         0.1       , 0.1       ],
        [0.14142136, 0.14142136, 0.14142136, ..., 0.14142136,
         0.14142136, 0.14142136],
        ...,
        [3.15753068, 3.15753068, 3.15753068, ..., 3.15753068,
         3.15753068, 3.15753068],
        [3.1