#Numpy

Numpy, es una combinación de palabras, `Numerical` y `Python`. Es uno de los más importantes paquetes en Python para el computo númerico.
La mayoría de los paquetes que proveen cálculos científicos utilizan objetos **NumPy** como elemento para intercambio de datos.

Estás son algunos elementos que utilizaremos con NumPy:

* **ndarray**: Una eficiente matriz *(Array=Arreglo)* multidimensional que provee operaciones aritmeticas entre arrays de forma flexible y rápidas.

* Funciones matemáticas para operar entre arrays de datos sin tener que escribir Loops. **AHHHH!**



&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; <img src="https://pm1.narvii.com/6240/84538693599c0871fec9e10f1fd0586fd3c284c4_hq.jpg"  width="250" height="250" />

* Herramientas para escribir array en disco y trabajarlos con archivos mapeados en memoria

* Algebra lineal, generación aleatoria de números, y algunas transformaciones.

Debido a que NumPy provee una facil de usar API para interactuar con otros lenguajes como C, es muy directo pasar datos de una libería externa en bajo nivel a Python.

Mientras que NumPy por si mismo no provee ninguna funcionalidad de modelado o científica, entender arrays NumPy y computo de arrays, te ayudará a usar otras herramientas como **Pandas** más eficientemente.

Principalmente nos focalizaremos en: 

* Operaciones entre arrays, data muning, y data cleaning, Filtering y transformaciones.

* Operaciones entre Arrays.

* Manimupación de datos mediante unión y consolidación (Join, Merge) utilizando datasets heterogéneos.

* Condiciones lógicas aplicadas a arrays.

Mientras que NumPy provee las bases para calculo computacional genérico, científicos de datos utilizan Pandas como el pilar de la mayoría de los desarrollos estadísticos y analíticos, especialmente con Datos tabulares. Panda también provee algunas funcionalidades que son específicas del dominio como manipulación de series.


## Comparando nmarrays y Python Arrays

Una de las razones por las que NumPy es tan importante para computo númerico en Python es debido a su eficiencia en el manejo de largos arrays (Arreglos) de datos.

NumPy internamente almacena los datos de forma contigua en bloques de memoria, independientemente de otros objetos Python. La librería Numpy de algoritmo puede operar en memoria sin perdida de performance. Los arrays de Numpy ocupan menos espacio que las listas de Python.

**Cuál será la razón?**

![](https://media1.tenor.com/images/4704d511d603640b82c2aeed0cc3af31/tenor.gif?itemid=11691381)

.. Sigamos

Las operaciones NumPy se comportan mejor en operaciones computacionales complejas en arrays sin la necesidad de utilizar loops de Python.

Para darles una idea de la diferencia de performance, veamos el siguiente código aplicando NumPy Arrays y listas Python


In [0]:
import numpy as np
my_arr = np.arange(1000000)  
my_list = list(range(1000000))

In [0]:
%time for _ in range(10): my_arr2 = my_arr * 2
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

## NumPy ndarray: Un obketo Array Multidimensional
Uno de las principales capacidad de NumPy es el N-Dimensional array, o también conodio como **ndarray**, cual es un rápido, y flexible container de largos datasets.
Los arreglos permite ejecutar operaciones matemáticas en un bloque completo usando sintaxis equivalente a elementos escalares.

Para darte una pequeña introducción de como NumPy puede gestionar arrays de forma similar que objetos Python, ejecutemos el siguiente código.


In [24]:
import numpy as np #Importamos Numpy
# Generamos Data random
data = np.random.randn(2, 3)
data

array([[ 0.5313886 , -1.20098546,  0.55315688],
       [ 0.15304392, -0.63413098,  1.27059148]])

In [25]:
data * 10

array([[  5.31388603, -12.00985459,   5.53156882],
       [  1.53043921,  -6.34130978,  12.7059148 ]])

In [27]:
data + data

array([[ 1.06277721, -2.40197092,  1.10631376],
       [ 0.30608784, -1.26826196,  2.54118296]])

In [7]:
data.shape

(2, 3)

In [28]:
data.dtype

dtype('float64')

## Creando Arrays

La forma más simplre de crear arrays es utilizando la función array. Dicha función acepta secuencia de objetos, incluidos otros arrays, y produce un nuevo array NumPy que contiene la data que se ha pasado. Por ejemplo una lista de candidatos para conversión:


In [29]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

Secuencias anidades, son convertidas a arrays multidimensionales.


In [0]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

In [32]:
arr2.ndim

2

In [33]:
arr2.shape

(2, 4)

Al menos que se especifique, **np.array** intenta inferir el mejor tipo de dato para el array creado. El tipo de dato es almacenado en un tipo especial de metadato. Por ejemplo:

In [0]:
arr1.dtype # Tipo de dato array1

In [0]:
arr2.dtype # Tipo de dato array2

Adicionalmente, **np.array** posee un número de funciones para crear nuevos arrays. Por ejemplo, crear arrays solo con ceros y unos respectivamente, con una dada longitud y forma.


In [38]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [39]:
np.zeros((3, 6)) #3 filas 6 columnas de ceros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

Con una longitud particular, **np.empty** crea un array sin inicializar y sin valores particulares.

In [42]:
np.empty((2, 3, 2)) #Array de 2 objetos de 3 filas y 2 columnas cada uno

array([[[2.72461315e-316, 1.06099790e-312],
        [2.33419537e-312, 2.22809558e-312],
        [2.12199580e-313, 2.41907520e-312]],

       [[1.06099790e-312, 2.44029516e-312],
        [2.05833592e-312, 2.14321575e-312],
        [2.97079411e-313, 0.00000000e+000]]])

In [37]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Tipo de datos

Puedes explicitamente convertir o castear un array de un tipo de dato a otro usando el método **astype** 


In [0]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

In [0]:
float_arr = arr.astype(np.float64) # Tomamos el array arr y lo casteamos a float
float_arr.dtype

## Aritmética con NumPy Array

Arrays son importante porque permite expresar operaciones batch en datos sin tener que escribir loops. Cualquier operación aritmética entre arrays del mismo tamaño aplica la operación a través de los elementos.


In [0]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
print (arr)
print ('\n')
print (arr * arr)
print ('\n')
print (arr - arr)
print ('\n')

In [0]:
1 / arr
arr ** 0.5

In [0]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

In [0]:
arr2 > arr #Devolverá un True o False

## Slicing e Indexing básico

Los índices en arrays NumPuy permiten seleccionar un subset individual de elementos. Los arrays simples son similares en comportamiento a las listas. Pero a medida que avanzamos, utilizar NumPy arrays es mucho mas útil

In [0]:
arr = np.arange(10)
arr

In [0]:
print (arr[5])
print (arr[5:8])
arr[5:8] = 12
print (arr)

El slice vacío asignará el mismo valor a todo el array


In [62]:
arr_slice = np.zeros(10)
arr_slice[:] = 64
arr_slice

array([64., 64., 64., 64., 64., 64., 64., 64., 64., 64.])

Con arrays de mayor dimensión, tienes muchas opciones. En un array de dos dimensiones, los elementos de cada índice no son más escalare, sino arrays de una dimensión.


In [63]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

Una forma fácil de ver los arrays multidimensionales es por ejemplo de la siguiente forma.
Tomamos el Eje 0 (axis 0) como las filas, y el Eje 1 (axis 1) como las columnas

<img src="https://github.com/al34n1x/datascience/blob/master/img/array.png?raw=true" width="400" height="300" />



En un array multidimensional, si omitimos un índice, el objeto que se retorna, sera un array de una dimensión inferior, consistiendo en toda los datos cruzados en las dimensiones superiores, por ejemplo en un array de 2 x 2 x 3: 


## Indexing con Slicing

Indices y Slices funcionan de la misma manera en arrays que en listas.
Así mismo podemos combinar el uso de índices con slices para extraer subitems de posiciones específicas del array.

In [0]:
print (arr2d)
print ('\n')
arr2d[:2, 1:] # Del primer item extraemos los nùmeros desde la posición 0 a 2, y del segundo ítem del array extraemos desde la posición 1 en adelante

Cuando rebanamos de esta forma, obtenemos vista de arrays dentro del mismo numero de dimensiones. Mezclando índices enteros y slides, podes obtener  rebanadas de una dimensión inferior.

Por ejemplo, puedo seleccionar la segunda fila pero solo las primeras dos columnas de la misma mediante la siguiente sentencia.


In [0]:
arr2d[1, :2]

Similarmente, puedes seleccionar la tercera columna pero solo la primera fila con la siguiente sentencia.



In [0]:
print (arr2d)
print ('\n')
arr2d[:2, 2]

In [0]:
print (arr2d)
print ('\n')
arr2d[:, :1] #Que me mostrará?

## Slicing en array de dos dimensiones

Este gráfico puede ayudarte durante tu trabajo desarrollando código con NumPy.


<img src="https://github.com/al34n1x/datascience/blob/master/img/array_shapes.png?raw=true" width="380" height="400" />


In [82]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

## Indices Booleanos

Consideremos el siguiente 

Let’s consider an example where we have some data in an array and an array of names with duplicates. I’m going to use here the randn function in numpy.random to generate some random normally distributed data: